name: Deploy to WordPress SVN

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      # Step 1: Set up Node.js (use the latest stable version)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'  # Use latest LTS version of Node.js

      # Step 2: Generate readme.txt using the Node.js script in .github/scripts/
      - name: Generate readme.txt
        run: node .github/scripts/generate-readme.js

      # Step 3: WordPress Plugin Deploy
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.WORDPRESS_USERNAME }}
          SVN_USERNAME: ${{ secrets.WORDPRESS_PASSWORD }}
          SLUG: discontinued-products
